# Python with UV Image
FROM ghcr.io/astral-sh/uv:python3.14-bookworm

# Setup environment variables
ENV APP_HOST=0.0.0.0
ENV APP_PORT=8000
# User
ENV USER=junkben
# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1
# Copy from the cache instead of linking
ENV UV_LINK_MODE=copy
# Virtual env path
ENV UV_PROJECT_ENVIRONMENT=/home/$USER/.venv
# Add uv dependencies to PATH
ENV PATH="${UV_PROJECT_ENVIRONMENT}/bin:${PATH}"

# Install common dev dependencies and clean up temp stuff
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential curl git vim \
        bind9-utils ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    # Setup user, make work dir, gives perms to user
    && groupadd --gid 999 $USER \
    && useradd --gid 999 --uid 999 --create-home --shell /bin/bash $USER \
    && mkdir -p /workspace \
    && chown -R $USER:$USER /home/$USER /workspace
    
# Project goes into `/workspace`
WORKDIR /workspace

# Install the project's dependencies using the lockfile and settings
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --no-install-project --frozen

# Then, add the rest of the project source code and install it
# Installing separately from its dependencies allows optimal layer caching
COPY --chown=$USER:$USER . ./
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen

# Use the user
USER $USER

# Run the FastAPI application by default
# Uses `uv run` to sync dependencies on startup
# Uses `fastapi dev` to enable hot-reloading when the `watch` sync occurs
# Uses `--host` to allow access from outside the container
# Note in production, you should use `fastapi run` instead
CMD ["uv", "run", "fastapi", "dev", "--host", "${APP_HOST}", "--port", "${APP_PORT}"]